name: Install StartLeft
description: 'Install StartLeft'
inputs:
  python-version:
    description: 'Python Version'
    required: true

runs:
  using: "composite"
  steps:

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}

      - name: Ensure pip is up-to-date
        run: python -m ensurepip --upgrade
        shell: bash

      - name: Upgrade setuptools for compatibility with setuptools-scm
        run: python -m pip install --upgrade setuptools
        shell: bash

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@55fcdfa9328aed658432c22011bec2873cd8e69f # Securely point to hash commit for v1

      - name: Install dependencies
        run:  python -m pip install . && python -m pip install -e ".[setup,test]"
        shell: bash


